apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: peter-shop

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: seckill

resources:
  - namespace.yaml
  - shared
  - infra
  - api-gateway
  - user-service
  - seckill-service

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/enableServiceLinks
        value: false

replacements:
  - source:
      kind: Service
      name: user-service
      fieldPath: spec.ports.0.port
    targets:
      - select:
          kind: ConfigMap
          name: api-gateway-config
        fieldPaths:
          - data.UPSTREAM_USER_ADDR
        options:
          delimiter: ":"
          index: 2
  - source:
      kind: Service
      name: seckill-service
      fieldPath: spec.ports.0.port
    targets:
      - select:
          kind: ConfigMap
          name: api-gateway-config
        fieldPaths:
          - data.UPSTREAM_SECKILL_ADDR
        options:
          delimiter: ":"
          index: 2
