apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd
    spec:
      containers:
        - name: etcd
          image: gcr.io/etcd-development/etcd:v3.5.17
          command:
            - /usr/local/bin/etcd
          envFrom:
            - configMapRef:
                name: etcd-config
          ports:
            - containerPort: 2379
              name: etcd-client
          readinessProbe:
            exec:
              command: ["etcdctl", "endpoint", "health"]
            initialDelaySeconds: 5
            periodSeconds: 5