apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: etcd-config
    envs:
      - etcd.properties

labels:
  - pairs:
      app.kubernetes.io/component: etcd
      app.kubernetes.io/part-of: infra
    includeTemplates: true