apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: infra
    envs:
      - infra.properties

secretGenerator:
  - name: credentials
    envs:
      - credentials.properties
